///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TestPlayer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchExistingPlayer recording.
    /// </summary>
    [TestModule("c342954c-0007-417c-a2f2-38c28beb3a62", ModuleType.Recording, 1)]
    public partial class SearchExistingPlayer : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TestPlayerRepository repository.
        /// </summary>
        public static TestPlayerRepository repo = TestPlayerRepository.Instance;

        static SearchExistingPlayer instance = new SearchExistingPlayer();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchExistingPlayer()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchExistingPlayer Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RechercheClient23101456.Name' at 75;7.", repo.RechercheClient23101456.NameInfo, new RecordItemIndex(0));
            repo.RechercheClient23101456.Name.Click("75;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'RANO000' with focus on 'RechercheClient23101456.Name'.", repo.RechercheClient23101456.NameInfo, new RecordItemIndex(1));
            repo.RechercheClient23101456.Name.PressKeys("RANO000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RechercheClient23101456.FirstName' at 69;8.", repo.RechercheClient23101456.FirstNameInfo, new RecordItemIndex(2));
            repo.RechercheClient23101456.FirstName.Click("69;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'REX000' with focus on 'RechercheClient23101456.FirstName'.", repo.RechercheClient23101456.FirstNameInfo, new RecordItemIndex(3));
            repo.RechercheClient23101456.FirstName.PressKeys("REX000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RechercheClient23101456.ButtonOK' at 38;15.", repo.RechercheClient23101456.ButtonOKInfo, new RecordItemIndex(4));
            repo.RechercheClient23101456.ButtonOK.Click("38;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
