///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestPlayer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestPlayerRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("4958389b-0572-4dce-bb3d-6a1e072c8e7a")]
    public partial class TestPlayerRepository : RepoGenBaseFolder
    {
        static TestPlayerRepository instance = new TestPlayerRepository();
        TestPlayerRepositoryFolders.MotDePasseAppFolder _motdepasse;
        TestPlayerRepositoryFolders.VIPlayers23101456AppFolder _viplayers23101456;
        TestPlayerRepositoryFolders.PlayerAppFolder _player;
        TestPlayerRepositoryFolders.ConfirmerAppFolder _confirmer;
        TestPlayerRepositoryFolders.Form1AppFolder _form1;
        TestPlayerRepositoryFolders.RechercheClient23101456AppFolder _rechercheclient23101456;
        TestPlayerRepositoryFolders.GestionDesComptesJoueurs23101456AppFolder _gestiondescomptesjoueurs23101456;

        /// <summary>
        /// Gets the singleton class instance representing the TestPlayerRepository element repository.
        /// </summary>
        [RepositoryFolder("4958389b-0572-4dce-bb3d-6a1e072c8e7a")]
        public static TestPlayerRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestPlayerRepository() 
            : base("TestPlayerRepository", "/", null, 0, false, "4958389b-0572-4dce-bb3d-6a1e072c8e7a", ".\\RepositoryImages\\TestPlayerRepository4958389b.rximgres")
        {
            _motdepasse = new TestPlayerRepositoryFolders.MotDePasseAppFolder(this);
            _viplayers23101456 = new TestPlayerRepositoryFolders.VIPlayers23101456AppFolder(this);
            _player = new TestPlayerRepositoryFolders.PlayerAppFolder(this);
            _confirmer = new TestPlayerRepositoryFolders.ConfirmerAppFolder(this);
            _form1 = new TestPlayerRepositoryFolders.Form1AppFolder(this);
            _rechercheclient23101456 = new TestPlayerRepositoryFolders.RechercheClient23101456AppFolder(this);
            _gestiondescomptesjoueurs23101456 = new TestPlayerRepositoryFolders.GestionDesComptesJoueurs23101456AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4958389b-0572-4dce-bb3d-6a1e072c8e7a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MotDePasse folder.
        /// </summary>
        [RepositoryFolder("5cfc46ca-ec02-429b-9fcb-ac91df255d32")]
        public virtual TestPlayerRepositoryFolders.MotDePasseAppFolder MotDePasse
        {
            get { return _motdepasse; }
        }

        /// <summary>
        /// The VIPlayers23101456 folder.
        /// </summary>
        [RepositoryFolder("8ef6c1ec-c69a-4fa2-9551-a217ca411713")]
        public virtual TestPlayerRepositoryFolders.VIPlayers23101456AppFolder VIPlayers23101456
        {
            get { return _viplayers23101456; }
        }

        /// <summary>
        /// The Player folder.
        /// </summary>
        [RepositoryFolder("48f1ff4e-4dc4-4d62-9651-402663eec736")]
        public virtual TestPlayerRepositoryFolders.PlayerAppFolder Player
        {
            get { return _player; }
        }

        /// <summary>
        /// The Confirmer folder.
        /// </summary>
        [RepositoryFolder("dcf6f224-9c94-4d4d-af98-af51d87dc4a5")]
        public virtual TestPlayerRepositoryFolders.ConfirmerAppFolder Confirmer
        {
            get { return _confirmer; }
        }

        /// <summary>
        /// The Form1 folder.
        /// </summary>
        [RepositoryFolder("1c83a2ed-a877-48df-a7e8-2530cb91ec38")]
        public virtual TestPlayerRepositoryFolders.Form1AppFolder Form1
        {
            get { return _form1; }
        }

        /// <summary>
        /// The RechercheClient23101456 folder.
        /// </summary>
        [RepositoryFolder("0b19c5d5-a914-4368-a581-caa8854b5ffa")]
        public virtual TestPlayerRepositoryFolders.RechercheClient23101456AppFolder RechercheClient23101456
        {
            get { return _rechercheclient23101456; }
        }

        /// <summary>
        /// The GestionDesComptesJoueurs23101456 folder.
        /// </summary>
        [RepositoryFolder("b3a77fa1-3e1c-4d31-b124-949eb0546667")]
        public virtual TestPlayerRepositoryFolders.GestionDesComptesJoueurs23101456AppFolder GestionDesComptesJoueurs23101456
        {
            get { return _gestiondescomptesjoueurs23101456; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TestPlayerRepositoryFolders
    {
        /// <summary>
        /// The MotDePasseAppFolder folder.
        /// </summary>
        [RepositoryFolder("5cfc46ca-ec02-429b-9fcb-ac91df255d32")]
        public partial class MotDePasseAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _passwordInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new MotDePasse  folder.
            /// </summary>
            public MotDePasseAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MotDePasse", "/form[@name='GetPassword']", parentFolder, 30000, null, true, "5cfc46ca-ec02-429b-9fcb-ac91df255d32", "")
            {
                _passwordInfo = new RepoItemInfo(this, "Password", "?/?/text[@name='Password']", "?/?/text[@name='Password']", 30000, null, "80ee1685-1e58-4b66-81bc-c5979bcc6e10");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/button[@name='Btn_OK']", "?/?/button[@name='Btn_OK']", 30000, null, "cc9b62d9-bb2b-4a69-ba56-68004df5f261");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5cfc46ca-ec02-429b-9fcb-ac91df255d32")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5cfc46ca-ec02-429b-9fcb-ac91df255d32")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("80ee1685-1e58-4b66-81bc-c5979bcc6e10")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("80ee1685-1e58-4b66-81bc-c5979bcc6e10")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("cc9b62d9-bb2b-4a69-ba56-68004df5f261")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("cc9b62d9-bb2b-4a69-ba56-68004df5f261")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The VIPlayers23101456AppFolder folder.
        /// </summary>
        [RepositoryFolder("8ef6c1ec-c69a-4fa2-9551-a217ca411713")]
        public partial class VIPlayers23101456AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menuitembonuspointInfo;
            RepoItemInfo _menuitemplayersInfo;
            RepoItemInfo _menuitemetatscentralisationInfo;
            RepoItemInfo _menuitemcalculdepointsInfo;
            RepoItemInfo _configurationInfo;
            RepoItemInfo _menuitemfenetreInfo;
            RepoItemInfo _playeridInfo;
            SomeButtonInfoClass _somebuttonInfo;

            /// <summary>
            /// Creates a new VIPlayers23101456  folder.
            /// </summary>
            public VIPlayers23101456AppFolder(RepoGenBaseFolder parentFolder) :
                    base("VIPlayers23101456", "/form[@name='Form1']", parentFolder, 30000, null, true, "8ef6c1ec-c69a-4fa2-9551-a217ca411713", "")
            {
                _menuitembonuspointInfo = new RepoItemInfo(this, "MenuItemBonusPoint", "?/?/menuitem[@name='BonusPoint1']", "?/?/menuitem[@name='BonusPoint1']", 30000, null, "9405e185-2c47-4c9b-b380-cac4eb6f704c");
                _menuitemplayersInfo = new RepoItemInfo(this, "MenuItemPlayers", "?/?/menuitem[@name='Players1']", "?/?/menuitem[@name='Players1']", 30000, null, "48a72c4a-2e4b-4889-97de-6d6b50fdf096");
                _menuitemetatscentralisationInfo = new RepoItemInfo(this, "MenuItemEtatsCentralisation", "?/?/menuitem[@name='Etatscentralisation1']", "?/?/menuitem[@name='Etatscentralisation1']", 30000, null, "7701bc70-9a4b-4723-b13d-1f037932124c");
                _menuitemcalculdepointsInfo = new RepoItemInfo(this, "MenuItemCalculDePoints", "?/?/menuitem[@name='Calculdepoints1']", "?/?/menuitem[@name='Calculdepoints1']", 30000, null, "010bd5ba-8e93-4890-8c23-31648b5522e6");
                _configurationInfo = new RepoItemInfo(this, "Configuration", "?/?/menuitem[@name='Configuration1']", "?/?/menuitem[@name='Configuration1']", 30000, null, "35b47efb-7233-4f8d-a46d-5dfc0a63b2be");
                _menuitemfenetreInfo = new RepoItemInfo(this, "MenuItemFenetre", "?/?/menuitem[@text='&Fenêtre']", "?/?/menuitem[@text='&Fenêtre']", 30000, null, "0f5da6da-26a0-4ed8-8280-ea7f07857f00");
                _playeridInfo = new RepoItemInfo(this, "PlayerID", "form[@name='Player_GstPlJou']//container[@name='tsCivil']/container[@name='Panel9']/?/?/text[@name='DBText2']", ".//text[@name='DBText2']", 30000, null, "77243a68-7211-4d9d-9636-efd81e08b510");
                _somebuttonInfo = new SomeButtonInfoClass(this);
            }

            /// <summary>
            /// The SomeButtonInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("f8dea9ad-0492-4ccd-93fa-b600e6bcf775")]
            public class SomeButtonInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SomeButtonInfoClass class constructor.
                /// </summary>
                public SomeButtonInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SomeButton", "form[@name='Player_GstPlJou']//container[@name='tsCivil']/container[@name='DBNavigator1']/button[8]", 30000, null, "f8dea9ad-0492-4ccd-93fa-b600e6bcf775")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("e19df7e0-0cde-4fa1-bc84-6ca7ead59879")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("e19df7e0-0cde-4fa1-bc84-6ca7ead59879");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e19df7e0-0cde-4fa1-bc84-6ca7ead59879")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e19df7e0-0cde-4fa1-bc84-6ca7ead59879", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8ef6c1ec-c69a-4fa2-9551-a217ca411713")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8ef6c1ec-c69a-4fa2-9551-a217ca411713")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItemBonusPoint item.
            /// </summary>
            [RepositoryItem("9405e185-2c47-4c9b-b380-cac4eb6f704c")]
            public virtual Ranorex.MenuItem MenuItemBonusPoint
            {
                get
                {
                    return _menuitembonuspointInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemBonusPoint item info.
            /// </summary>
            [RepositoryItemInfo("9405e185-2c47-4c9b-b380-cac4eb6f704c")]
            public virtual RepoItemInfo MenuItemBonusPointInfo
            {
                get
                {
                    return _menuitembonuspointInfo;
                }
            }

            /// <summary>
            /// The MenuItemPlayers item.
            /// </summary>
            [RepositoryItem("48a72c4a-2e4b-4889-97de-6d6b50fdf096")]
            public virtual Ranorex.MenuItem MenuItemPlayers
            {
                get
                {
                    return _menuitemplayersInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemPlayers item info.
            /// </summary>
            [RepositoryItemInfo("48a72c4a-2e4b-4889-97de-6d6b50fdf096")]
            public virtual RepoItemInfo MenuItemPlayersInfo
            {
                get
                {
                    return _menuitemplayersInfo;
                }
            }

            /// <summary>
            /// The MenuItemEtatsCentralisation item.
            /// </summary>
            [RepositoryItem("7701bc70-9a4b-4723-b13d-1f037932124c")]
            public virtual Ranorex.MenuItem MenuItemEtatsCentralisation
            {
                get
                {
                    return _menuitemetatscentralisationInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemEtatsCentralisation item info.
            /// </summary>
            [RepositoryItemInfo("7701bc70-9a4b-4723-b13d-1f037932124c")]
            public virtual RepoItemInfo MenuItemEtatsCentralisationInfo
            {
                get
                {
                    return _menuitemetatscentralisationInfo;
                }
            }

            /// <summary>
            /// The MenuItemCalculDePoints item.
            /// </summary>
            [RepositoryItem("010bd5ba-8e93-4890-8c23-31648b5522e6")]
            public virtual Ranorex.MenuItem MenuItemCalculDePoints
            {
                get
                {
                    return _menuitemcalculdepointsInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemCalculDePoints item info.
            /// </summary>
            [RepositoryItemInfo("010bd5ba-8e93-4890-8c23-31648b5522e6")]
            public virtual RepoItemInfo MenuItemCalculDePointsInfo
            {
                get
                {
                    return _menuitemcalculdepointsInfo;
                }
            }

            /// <summary>
            /// The Configuration item.
            /// </summary>
            [RepositoryItem("35b47efb-7233-4f8d-a46d-5dfc0a63b2be")]
            public virtual Ranorex.MenuItem Configuration
            {
                get
                {
                    return _configurationInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Configuration item info.
            /// </summary>
            [RepositoryItemInfo("35b47efb-7233-4f8d-a46d-5dfc0a63b2be")]
            public virtual RepoItemInfo ConfigurationInfo
            {
                get
                {
                    return _configurationInfo;
                }
            }

            /// <summary>
            /// The MenuItemFenetre item.
            /// </summary>
            [RepositoryItem("0f5da6da-26a0-4ed8-8280-ea7f07857f00")]
            public virtual Ranorex.MenuItem MenuItemFenetre
            {
                get
                {
                    return _menuitemfenetreInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemFenetre item info.
            /// </summary>
            [RepositoryItemInfo("0f5da6da-26a0-4ed8-8280-ea7f07857f00")]
            public virtual RepoItemInfo MenuItemFenetreInfo
            {
                get
                {
                    return _menuitemfenetreInfo;
                }
            }

            /// <summary>
            /// The PlayerID item.
            /// </summary>
            [RepositoryItem("77243a68-7211-4d9d-9636-efd81e08b510")]
            public virtual Ranorex.Text PlayerID
            {
                get
                {
                    return _playeridInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PlayerID item info.
            /// </summary>
            [RepositoryItemInfo("77243a68-7211-4d9d-9636-efd81e08b510")]
            public virtual RepoItemInfo PlayerIDInfo
            {
                get
                {
                    return _playeridInfo;
                }
            }

            /// <summary>
            /// The SomeButton item.
            /// </summary>
            [RepositoryItem("f8dea9ad-0492-4ccd-93fa-b600e6bcf775")]
            public virtual Ranorex.Button SomeButton
            {
                get
                {
                    return _somebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton item info.
            /// </summary>
            [RepositoryItemInfo("f8dea9ad-0492-4ccd-93fa-b600e6bcf775")]
            public virtual SomeButtonInfoClass SomeButtonInfo
            {
                get
                {
                    return _somebuttonInfo;
                }
            }
        }

        /// <summary>
        /// The PlayerAppFolder folder.
        /// </summary>
        [RepositoryFolder("48f1ff4e-4dc4-4d62-9651-402663eec736")]
        public partial class PlayerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _quitterInfo;
            RepoItemInfo _gestionInfo;
            RepoItemInfo _joueurInfo;

            /// <summary>
            /// Creates a new Player  folder.
            /// </summary>
            public PlayerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Player", "/contextmenu[@processname='Player']", parentFolder, 30000, null, false, "48f1ff4e-4dc4-4d62-9651-402663eec736", "")
            {
                _quitterInfo = new RepoItemInfo(this, "Quitter", "?/?/menuitem[@accessiblename='Quitter']", "?/?/menuitem[@accessiblename='Quitter']", 30000, null, "15e510f4-dd39-4597-8d4f-c7edbd41bd78");
                _gestionInfo = new RepoItemInfo(this, "Gestion", "?/?/menuitem[@accessiblename='Gestion']", "?/?/menuitem[@accessiblename='Gestion']", 30000, null, "3e54bf3c-fcdc-4bc3-8d8d-e6afe548212a");
                _joueurInfo = new RepoItemInfo(this, "Joueur", "?/?/menuitem[@accessiblename='Joueur...']", "?/?/menuitem[@accessiblename='Joueur...']", 30000, null, "7b7c2512-2061-47f7-9c5c-353017bcdf47");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("48f1ff4e-4dc4-4d62-9651-402663eec736")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("48f1ff4e-4dc4-4d62-9651-402663eec736")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Quitter item.
            /// </summary>
            [RepositoryItem("15e510f4-dd39-4597-8d4f-c7edbd41bd78")]
            public virtual Ranorex.MenuItem Quitter
            {
                get
                {
                    return _quitterInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Quitter item info.
            /// </summary>
            [RepositoryItemInfo("15e510f4-dd39-4597-8d4f-c7edbd41bd78")]
            public virtual RepoItemInfo QuitterInfo
            {
                get
                {
                    return _quitterInfo;
                }
            }

            /// <summary>
            /// The Gestion item.
            /// </summary>
            [RepositoryItem("3e54bf3c-fcdc-4bc3-8d8d-e6afe548212a")]
            public virtual Ranorex.MenuItem Gestion
            {
                get
                {
                    return _gestionInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Gestion item info.
            /// </summary>
            [RepositoryItemInfo("3e54bf3c-fcdc-4bc3-8d8d-e6afe548212a")]
            public virtual RepoItemInfo GestionInfo
            {
                get
                {
                    return _gestionInfo;
                }
            }

            /// <summary>
            /// The Joueur item.
            /// </summary>
            [RepositoryItem("7b7c2512-2061-47f7-9c5c-353017bcdf47")]
            public virtual Ranorex.MenuItem Joueur
            {
                get
                {
                    return _joueurInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Joueur item info.
            /// </summary>
            [RepositoryItemInfo("7b7c2512-2061-47f7-9c5c-353017bcdf47")]
            public virtual RepoItemInfo JoueurInfo
            {
                get
                {
                    return _joueurInfo;
                }
            }
        }

        /// <summary>
        /// The ConfirmerAppFolder folder.
        /// </summary>
        [RepositoryFolder("dcf6f224-9c94-4d4d-af98-af51d87dc4a5")]
        public partial class ConfirmerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonouiInfo;
            RepoItemInfo _buttonnonInfo;

            /// <summary>
            /// Creates a new Confirmer  folder.
            /// </summary>
            public ConfirmerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Confirmer", "/form[@name='none']", parentFolder, 30000, null, true, "dcf6f224-9c94-4d4d-af98-af51d87dc4a5", "")
            {
                _buttonouiInfo = new RepoItemInfo(this, "ButtonOui", "button[@name='Yes']", "button[@name='Yes']", 30000, null, "48c9be2d-7aba-4908-9b4f-0b66ae195121");
                _buttonnonInfo = new RepoItemInfo(this, "ButtonNon", "button[@name='No']", "button[@name='No']", 30000, null, "f49108d2-f01e-444f-b17a-af1f22a4653c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dcf6f224-9c94-4d4d-af98-af51d87dc4a5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dcf6f224-9c94-4d4d-af98-af51d87dc4a5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOui item.
            /// </summary>
            [RepositoryItem("48c9be2d-7aba-4908-9b4f-0b66ae195121")]
            public virtual Ranorex.Button ButtonOui
            {
                get
                {
                    return _buttonouiInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOui item info.
            /// </summary>
            [RepositoryItemInfo("48c9be2d-7aba-4908-9b4f-0b66ae195121")]
            public virtual RepoItemInfo ButtonOuiInfo
            {
                get
                {
                    return _buttonouiInfo;
                }
            }

            /// <summary>
            /// The ButtonNon item.
            /// </summary>
            [RepositoryItem("f49108d2-f01e-444f-b17a-af1f22a4653c")]
            public virtual Ranorex.Button ButtonNon
            {
                get
                {
                    return _buttonnonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNon item info.
            /// </summary>
            [RepositoryItemInfo("f49108d2-f01e-444f-b17a-af1f22a4653c")]
            public virtual RepoItemInfo ButtonNonInfo
            {
                get
                {
                    return _buttonnonInfo;
                }
            }
        }

        /// <summary>
        /// The Form1AppFolder folder.
        /// </summary>
        [RepositoryFolder("1c83a2ed-a877-48df-a7e8-2530cb91ec38")]
        public partial class Form1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _imbacksplashInfo;

            /// <summary>
            /// Creates a new Form1  folder.
            /// </summary>
            public Form1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form1", "/form[@controlname='Form1']", parentFolder, 30000, null, true, "1c83a2ed-a877-48df-a7e8-2530cb91ec38", "")
            {
                _imbacksplashInfo = new RepoItemInfo(this, "ImBackSplash", "picture[@name='ImBackSplash']", "picture[@name='ImBackSplash']", 30000, null, "82febdbf-e4c6-4c64-a45f-7f67e393106b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1c83a2ed-a877-48df-a7e8-2530cb91ec38")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1c83a2ed-a877-48df-a7e8-2530cb91ec38")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ImBackSplash item.
            /// </summary>
            [RepositoryItem("82febdbf-e4c6-4c64-a45f-7f67e393106b")]
            public virtual Ranorex.Picture ImBackSplash
            {
                get
                {
                    return _imbacksplashInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The ImBackSplash item info.
            /// </summary>
            [RepositoryItemInfo("82febdbf-e4c6-4c64-a45f-7f67e393106b")]
            public virtual RepoItemInfo ImBackSplashInfo
            {
                get
                {
                    return _imbacksplashInfo;
                }
            }
        }

        /// <summary>
        /// The RechercheClient23101456AppFolder folder.
        /// </summary>
        [RepositoryFolder("0b19c5d5-a914-4368-a581-caa8854b5ffa")]
        public partial class RechercheClient23101456AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nameInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new RechercheClient23101456  folder.
            /// </summary>
            public RechercheClient23101456AppFolder(RepoGenBaseFolder parentFolder) :
                    base("RechercheClient23101456", "/form[@name='GetCustomerL']", parentFolder, 30000, null, true, "0b19c5d5-a914-4368-a581-caa8854b5ffa", "")
            {
                _nameInfo = new RepoItemInfo(this, "Name", "container[@name='Panel1']/?/?/text[@name='Name']", ".//text[@name='Name']", 30000, null, "3bd26178-5ce7-4f27-ade0-7d3c709ed5af");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "container[@name='Panel1']/?/?/text[@name='FirstName']", ".//text[@name='FirstName']", 30000, null, "ea4f5a7b-4b7b-4ecb-bd9b-ba4321c64fc6");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/button[@name='Btn_OK']", "?/?/button[@name='Btn_OK']", 30000, null, "98475995-22ff-4e78-8868-f85035ecab17");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0b19c5d5-a914-4368-a581-caa8854b5ffa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0b19c5d5-a914-4368-a581-caa8854b5ffa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("3bd26178-5ce7-4f27-ade0-7d3c709ed5af")]
            public virtual Ranorex.Text Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("3bd26178-5ce7-4f27-ade0-7d3c709ed5af")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("ea4f5a7b-4b7b-4ecb-bd9b-ba4321c64fc6")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("ea4f5a7b-4b7b-4ecb-bd9b-ba4321c64fc6")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("98475995-22ff-4e78-8868-f85035ecab17")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("98475995-22ff-4e78-8868-f85035ecab17")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The GestionDesComptesJoueurs23101456AppFolder folder.
        /// </summary>
        [RepositoryFolder("b3a77fa1-3e1c-4d31-b124-949eb0546667")]
        public partial class GestionDesComptesJoueurs23101456AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonfermerInfo;

            /// <summary>
            /// Creates a new GestionDesComptesJoueurs23101456  folder.
            /// </summary>
            public GestionDesComptesJoueurs23101456AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GestionDesComptesJoueurs23101456", "/form[@name='Player_AccountManagement']", parentFolder, 30000, null, true, "b3a77fa1-3e1c-4d31-b124-949eb0546667", "")
            {
                _buttonfermerInfo = new RepoItemInfo(this, "ButtonFermer", "?/?/button[@name='BtnClose']", "?/?/button[@name='BtnClose']", 30000, null, "2d85da19-343f-45ad-a495-4f111e59a214");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b3a77fa1-3e1c-4d31-b124-949eb0546667")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b3a77fa1-3e1c-4d31-b124-949eb0546667")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonFermer item.
            /// </summary>
            [RepositoryItem("2d85da19-343f-45ad-a495-4f111e59a214")]
            public virtual Ranorex.Button ButtonFermer
            {
                get
                {
                    return _buttonfermerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonFermer item info.
            /// </summary>
            [RepositoryItemInfo("2d85da19-343f-45ad-a495-4f111e59a214")]
            public virtual RepoItemInfo ButtonFermerInfo
            {
                get
                {
                    return _buttonfermerInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
